/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitaptuyendoan;

/**
 *
 * @author Dell
 */
public class Baitaptuyendoan1 extends javax.swing.JFrame {

    /**
     * Creates new form Baitaptuyendoan1
     */
    //Khai báo các biến toàn cục
    long s1=0,s2=0,s=0; boolean kt1=false,kt2=false;
          //Tạo lớp tuyến đoạn chúng
    public class Tuyen extends Thread{
       int td; //lưu tuyến đoạn thứ mấy
       int[] a; //Mảng a cần tính tổnge
       public Tuyen(int td, int[] a){ //Tạo hàm tạo
           this.td=td;
           this.a=a;
       }
       public void run(){
         if(td==1){//nếu là tuyến 1
            int n=a.length; 
			//Tính nữa mảng đầu
            for(int i=0;i<n/2;i++)
                s1=s1+a[i];
            kt1=true;
         }
         if(td==2){////nếu là tuyến 2
            int n=a.length; 
			//Tính nữa mảng sau
            for(int i=n/2;i<n;i++)
                s2=s2+a[i];
            kt2=true;
        }
    }
}


    public Baitaptuyendoan1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmang = new javax.swing.JLabel();
        lblkq1 = new javax.swing.JLabel();
        lblkq2 = new javax.swing.JLabel();
        lbltong = new javax.swing.JLabel();
        txtmang = new javax.swing.JTextField();
        txtkq1 = new javax.swing.JTextField();
        txtkq2 = new javax.swing.JTextField();
        txttong = new javax.swing.JTextField();
        btntinh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblmang.setText("Nhập vào một mảng");

        lblkq1.setText("Kết quả tuyến đoạn 1:");

        lblkq2.setText("Kết quả tuyến đoạn 2:");

        lbltong.setText("Tổng các phần tử");

        txtmang.setToolTipText("");
        txtmang.setName(""); // NOI18N
        txtmang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmangActionPerformed(evt);
            }
        });

        btntinh.setText("Tính");
        btntinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbltong)
                    .addComponent(lblkq2)
                    .addComponent(lblkq1)
                    .addComponent(lblmang))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmang, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtkq2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                                .addComponent(txtkq1)))
                        .addGap(44, 44, 44))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txttong)
                                .addGap(279, 279, 279))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btntinh, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(418, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmang)
                    .addComponent(txtmang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkq1)
                    .addComponent(txtkq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblkq2)
                    .addComponent(txtkq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltong)
                    .addComponent(txttong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btntinh)
                .addContainerGap(99, Short.MAX_VALUE))
        );

        lblmang.getAccessibleContext().setAccessibleName("");
        lblkq1.getAccessibleContext().setAccessibleName("");
        lblkq2.getAccessibleContext().setAccessibleName("");
        lbltong.getAccessibleContext().setAccessibleName("");
        txtmang.getAccessibleContext().setAccessibleName("");
        txtkq1.getAccessibleContext().setAccessibleName("");
        txtkq2.getAccessibleContext().setAccessibleName("");
        txttong.getAccessibleContext().setAccessibleName("");
        btntinh.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtmangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmangActionPerformed

    private void btntinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntinhActionPerformed
        // TODO add your handling code here:
        String st = txtmang.getText();
        String[] ds= st.split(";");
        
        int n =ds.length;
        //Khai báo mảng số nguyên
        int[] a=new int[ds.length];
        //Đổi mảng chuỗi sang mảng số
        for(int i=0;i<n;i++){
           a[i]=Integer.parseInt(ds[i]);
        }

            Tuyen t1 = new Tuyen(1,a);
            t1.start();
            Tuyen t2 = new Tuyen(2,a);
            t2.start(); 
        
            
          while(true){
            System.out.println("Dang doi............");
          if(kt1==true&&kt2==true){
            s=s1+s2; 
            //System.out.println("s1="+s1);
            // System.out.println("s2="+s2);
            // System.out.println("s="+s);
            txtkq1.setText(String.valueOf(s1));
            txtkq2.setText(String.valueOf(s2));
            txttong.setText(String.valueOf(s));
          break;
        }
    }//GEN-LAST:event_btntinhActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Baitaptuyendoan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Baitaptuyendoan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Baitaptuyendoan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Baitaptuyendoan1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Baitaptuyendoan1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btntinh;
    private javax.swing.JLabel lblkq1;
    private javax.swing.JLabel lblkq2;
    private javax.swing.JLabel lblmang;
    private javax.swing.JLabel lbltong;
    private javax.swing.JTextField txtkq1;
    private javax.swing.JTextField txtkq2;
    private javax.swing.JTextField txtmang;
    private javax.swing.JTextField txttong;
    // End of variables declaration//GEN-END:variables
}
