/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package baitaptuyendoan;

import java.time.LocalTime;

/**
 *
 * @author Dell
 */
public class frmtuyendoan42 extends javax.swing.JFrame {

    /**
     * Creates new form frmtuyendoan42
     */
    int h, m, s, ms;
    boolean kt1 = false, kt2 = false, kt3 = false, kt4 = false;

    public class Lop extends Thread {

        int i, a[];

        public Lop(int i, int[] a) {
            this.i = i;
            this.a = a;
        }

        public void run() {
            if (i == 1) {
                try {
                    while (true) {
                        labelHour.setText(String.valueOf(a[0]));
                        Thread.sleep(1000 * 3600);
                        a[0]++;
                        if (a[0] == 24) {
                            a[0] = 0;
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            if (i == 2) {
                try {
                    while (true) {
                        labelMinute.setText(String.valueOf(a[1]));
                        Thread.sleep(60000);
                        a[1]++;
                        if (a[1] == 60) {
                            a[1] = 0;
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            if (i == 3) {
                try {
                    while (true) {
                        labelSecond.setText(String.valueOf(a[2]));
                        Thread.sleep(1000);
                        a[2]++;
                        if (a[2] == 60) {
                            a[2] = 0;
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            if (i == 4) {
                try {
                    while (true) {
                        labelMiniSecond.setText(String.valueOf(a[3]));
                        Thread.sleep(1);
                        a[3]++;
                        if (a[3] == 1000) {
                            a[3] = 0;
                        }
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }

        }
    }        
    public frmtuyendoan42() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelHour = new javax.swing.JLabel();
        labelMinute = new javax.swing.JLabel();
        labelSecond = new javax.swing.JLabel();
        labelMiniSecond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        labelHour.setBackground(new java.awt.Color(51, 51, 255));
        labelHour.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHour.setText("jLabel1");

        labelMinute.setBackground(new java.awt.Color(51, 51, 255));
        labelMinute.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMinute.setText("jLabel2");

        labelSecond.setBackground(new java.awt.Color(51, 51, 255));
        labelSecond.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelSecond.setText("jLabel3");

        labelMiniSecond.setBackground(new java.awt.Color(51, 51, 255));
        labelMiniSecond.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelMiniSecond.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(labelHour)
                .addGap(18, 18, 18)
                .addComponent(labelMinute)
                .addGap(28, 28, 28)
                .addComponent(labelSecond)
                .addGap(37, 37, 37)
                .addComponent(labelMiniSecond)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHour)
                    .addComponent(labelMinute)
                    .addComponent(labelSecond)
                    .addComponent(labelMiniSecond))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        String time = LocalTime.now().toString();
        String[] ds = time.split("\\W+");
        int[] a = new int[ds.length];
        for (int i = 0; i < ds.length; i++) {
            a[i] = Integer.parseInt(ds[i]);
        }
        a[2] = 0;
        a[3] = 0;
        for (int i = 1; i <= 4; i++) {
            Lop L1 = new Lop(i, a);
            L1.start();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmtuyendoan42.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmtuyendoan42.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmtuyendoan42.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmtuyendoan42.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmtuyendoan42().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelHour;
    private javax.swing.JLabel labelMiniSecond;
    private javax.swing.JLabel labelMinute;
    private javax.swing.JLabel labelSecond;
    // End of variables declaration//GEN-END:variables
}
