/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hoangthehuy;

import java.net.InetAddress;



/**
 *
 * @author Dell
 */
public class frmmay2_Huy extends javax.swing.JFrame {

    /**
     * Creates new form frmmay2_Huy
     */
    GuiNhan_Huy gn ;
    
    
        
    public frmmay2_Huy() {
        initComponents();
        gn = new GuiNhan_Huy();
        try{
            gn.MoCong(1260);
            TuyenNhan tnhan = new TuyenNhan();
            tnhan.start();
        }catch (Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textArea1 = new java.awt.TextArea();
        txtkqmay2 = new java.awt.TextField();
        label5 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Máy 2");

        label5.setText("KQ máy 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addComponent(txtkqmay2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtkqmay2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public class TuyenNhan extends Thread{
        public void run(){
            while(true){
                try{
                    String st = gn.nhan();
                    if(st != null && !st.isEmpty()){
                        String[] ds = st.split("[;]");

                        int n = Integer.parseInt(ds[0]);
                        int k = Integer.parseInt(ds[1]);

                        Tinh2_Huy t1 = new Tinh2_Huy(1, k, n-1);
                        t1.start();
                        Tinh2_Huy t2 = new Tinh2_Huy(2, k, n-1);
                        t2.start();

                        while(true){
                            System.out.println("Dang doi............");
                            if(kt1 && kt2){
                                s = s1+s2; 
                                txtkqmay2.setText(String.valueOf(s));
                                Send(String.valueOf(s));
                                break;
                            }
                        }

                    }
                } catch (Exception e){
                    e.printStackTrace();
                }
            }
        }
    }
    
    int C(int k, int n) {
        if (k == 0 || k == n) return 1;
        if (k == 1) return n;
        return C(k-1,n-1) + C(k,n-1);
    }
    
    int s1=0,s2=0,s=0; 
    boolean kt1 = false,kt2 = false;
    
    public class Tinh2_Huy extends Thread{
        int i,k,n;
        public Tinh2_Huy(int i,int k,int n){
            this.i=i;
            this.k=k;
            this.n=n;
        }
        public void run(){
            if(i==1){
                s1 = C(k,n-1);
                kt1=true;
            }
            if(i==2){
                s2 =C(k-1,n-1);
                kt2=true;
            }
        }
    }    
    public void Send(String mess){
        try{
            String ip = InetAddress.getLocalHost().getHostName();
            gn.Gui(mess,ip,1261);
        }
        catch (Exception e){
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmmay2_Huy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmmay2_Huy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmmay2_Huy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmmay2_Huy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmmay2_Huy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label5;
    private java.awt.TextArea textArea1;
    private java.awt.TextField txtkqmay2;
    // End of variables declaration//GEN-END:variables
}
