/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bank_client;

import bank_server.IBank;
import bean.TaiKhoanbean;
import java.rmi.Naming;
//import bo.ChiTietTaiKhoanbo;
//import bo.TaiKhoanbo;
import java.util.logging.Logger;
import java.util.logging.Level;
/**
 *
 * @author Dell
 */
public class frmChuyenKhoan extends javax.swing.JFrame {
    private String stk;
    private String stknguoinhan;
    /**
     * Creates new form frmChuyenKhoan
     */
    //TaiKhoanbo tkbo = new TaiKhoanbo();
    //ChiTietTaiKhoanbo cttkbo = new ChiTietTaiKhoanbo();
    public frmChuyenKhoan(String stk) {
        initComponents();
        this.stk = stk;
    }

    private frmChuyenKhoan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        btnReset = new java.awt.Button();
        btnEnter = new java.awt.Button();
        txtSoTienChuyen = new javax.swing.JTextField();
        txtSTKnhan = new javax.swing.JTextField();
        mess = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLyDo = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JPasswordField();
        btnCheck = new javax.swing.JButton();
        messTenTaiKhoanNhan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chuyển khoản");

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("STK nhận:");

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("Số tiền chuyển:");

        btnReset.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btnReset.setLabel("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnEnter.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btnEnter.setLabel("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        txtSoTienChuyen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSoTienChuyen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtSTKnhan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        mess.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        txtLyDo.setColumns(20);
        txtLyDo.setRows(5);
        jScrollPane1.setViewportView(txtLyDo);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Lý do:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nhập mật khẩu:");

        txtMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });

        messTenTaiKhoanNhan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messTenTaiKhoanNhan)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                        .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(txtSTKnhan)
                                    .addComponent(txtSoTienChuyen, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(btnCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSTKnhan, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnCheck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(messTenTaiKhoanNhan)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoTienChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtSTKnhan.setText("");
        txtSoTienChuyen.setText("");
        txtLyDo.setText("");
        txtMatKhau.setText("");
        mess.setText("");
        messTenTaiKhoanNhan.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        long stchuyen= Long.parseLong(txtSoTienChuyen.getText());
        long stht = 0;
        String matkhau = null;
        try {
            IBank b = (IBank) Naming.lookup("rmi://localhost/Bank");
            for(TaiKhoanbean s:b.getTaiKhoan(stk))
            {
                stht = s.getSoTien();
                matkhau= s.getMatKhau();
            }
        } catch (Exception ex) {
            Logger.getLogger(frmChuyenKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        stknguoinhan=txtSTKnhan.getText();
        String ghichu1= "Chuyển cho stk:"+stknguoinhan+"Lý do:"+txtLyDo.getText();
        String ghichu2= "Nhận từ:"+stk+"Lý do:"+txtLyDo.getText();
        long stnguoinhan = 0;
       
        try {
            IBank c = (IBank) Naming.lookup("rmi://localhost/Bank");
            for (TaiKhoanbean b:c.getTaiKhoan(stknguoinhan))
                stnguoinhan = b.getSoTien();
               
        } catch (Exception ex) {
            Logger.getLogger(frmChuyenKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        long soduht= stht - stchuyen;
        long sodunguoinhan= stnguoinhan + stchuyen;
        if(String.valueOf(txtMatKhau.getPassword()).equals(matkhau)){
            if(txtSTKnhan.getText().equals(stk)){
            mess.setText("trùng tài khoản");
            }else{
                if (stchuyen>0 && stchuyen<stht){
                    if(soduht > 50000){
                        try {
                            IBank b = (IBank) Naming.lookup("rmi://localhost/Bank");
                            if(b.updateSodu(stk, soduht)&&b.updateSodu(txtSTKnhan.getText(), sodunguoinhan)&& b.insertChuyenTien(stk, -stchuyen, ghichu1 ) && b.insertChuyenTien(txtSTKnhan.getText(),+stchuyen , ghichu2)){
                            mess.setText("Chuyển thành công !");
                            
                            txtSTKnhan.setText("");
                            txtSoTienChuyen.setText("");
                            txtLyDo.setText("");
                            txtMatKhau.setText("");
                            mess.setText("");
                            messTenTaiKhoanNhan.setText("");
                            }
                            else{
                            mess.setText("Lỗi hệ thống!");
                            }
                        } catch (Exception e) {
                        Logger.getLogger(frmChuyenKhoan.class.getName()).log(Level.SEVERE, null, e);
                        }
                    }else{
                        mess.setText("số dư không đủ dể chuyển");
                        }
                
                }else{
                mess.setText("sô tiền chuyển là âm hoặc lớn hơn số dư");             
                txtSoTienChuyen.setText("");
                }
            }
        }else{
        mess.setText("mật khẩu không đúng");
        txtMatKhau.setText("");
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        String tentk = null;
        try {
            IBank b = (IBank) Naming.lookup("rmi://localhost/Bank");
            for(TaiKhoanbean s:b.getTaiKhoan(txtSTKnhan.getText()))
               // stht = s.getSoTien();
            {
                  tentk= s.getHoten();
                  messTenTaiKhoanNhan.setText(tentk);
            }
        } catch (Exception ex) {
            Logger.getLogger(frmChuyenKhoan.class.getName()).log(Level.SEVERE, null, ex);
            messTenTaiKhoanNhan.setText("STK này không tồn tại vui lòng nhập lại!");
            txtSTKnhan.setText("");
        }
        
    }//GEN-LAST:event_btnCheckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChuyenKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private java.awt.Button btnEnter;
    private java.awt.Button btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel mess;
    private javax.swing.JLabel messTenTaiKhoanNhan;
    private javax.swing.JTextArea txtLyDo;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtSTKnhan;
    private javax.swing.JTextField txtSoTienChuyen;
    // End of variables declaration//GEN-END:variables
}
