/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.TaiKhoanbean;
import bo.ChiTietTaiKhoanbo;
import bo.TaiKhoanbo;
import java.util.logging.Logger;
import java.util.logging.Level;
/**
 *
 * @author Dell
 */
public class frmChuyenKhoan extends javax.swing.JFrame {
    private String stk;
    
    /**
     * Creates new form frmChuyenKhoan
     */
    TaiKhoanbo tkbo = new TaiKhoanbo();
    ChiTietTaiKhoanbo cttkbo = new ChiTietTaiKhoanbo();
    public frmChuyenKhoan(String stk) {
        initComponents();
        this.stk = stk;
    }

    private frmChuyenKhoan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        btnReset = new java.awt.Button();
        btnEnter = new java.awt.Button();
        txtSoTienChuyen = new javax.swing.JTextField();
        txtSTKnhan = new javax.swing.JTextField();
        mess = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chuyển khoản");

        label1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label1.setText("STK nhận:");

        label2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label2.setText("Số tiền chuyển:");

        btnReset.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btnReset.setLabel("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnEnter.setFont(new java.awt.Font("Dialog", 3, 18)); // NOI18N
        btnEnter.setLabel("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        txtSoTienChuyen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtSoTienChuyen.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        txtSTKnhan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        mess.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSTKnhan)
                    .addComponent(txtSoTienChuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(234, 234, 234)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                .addComponent(mess, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtSTKnhan, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSoTienChuyen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnReset, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                        .addComponent(btnEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(mess, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtSTKnhan.setText("");
        txtSoTienChuyen.setText("");
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        long stchuyen= Long.parseLong(txtSoTienChuyen.getText());
        long stht = 0;
        try {
            for(TaiKhoanbean s:tkbo.getTaiKhoan(stk))
                stht = s.getSoTien();
        } catch (Exception ex) {
            Logger.getLogger(frmChuyenKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        String ghichu1= "Chuyển";
        String ghichu2= "Nhận";
        long stnguoinhan = 0;
        String stknguoinhan=txtSTKnhan.getText();
        try {
            for (TaiKhoanbean b:tkbo.getTaiKhoan(stknguoinhan))
                stnguoinhan = b.getSoTien();
        } catch (Exception ex) {
            Logger.getLogger(frmChuyenKhoan.class.getName()).log(Level.SEVERE, null, ex);
        }
        long soduht= stht - stchuyen;
        long sodunguoinhan= stnguoinhan + stchuyen;
        if(txtSTKnhan.equals(stk)){
            mess.setText("trùng tài khoản");
        }else{
            if (stchuyen>0 && stchuyen<stht){
                if(soduht > 50000){
                    try {
                        if(tkbo.updateSodu(stk, soduht)&&tkbo.updateSodu(txtSTKnhan.getText(), sodunguoinhan)&& cttkbo.insertChuyenTien(stk, -stchuyen, ghichu1 ) && cttkbo.insertChuyenTien(txtSTKnhan.getText(),+stchuyen , ghichu2)){
                            mess.setText("Chuyển thành công !");
                        }
                        else{
                            mess.setText("Chuyển ko thành công!");
                        }
                    } catch (Exception e) {
                        Logger.getLogger(frmChuyenKhoan.class.getName()).log(Level.SEVERE, null, e);
                    }
                }else{
                    mess.setText("số dư không đủ dể chuyển");
                }
                
            }else{
                mess.setText("sô tiền chuyển là âm hoặc lớn hơn số dư");
            }
        }
    }//GEN-LAST:event_btnEnterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChuyenKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChuyenKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnEnter;
    private java.awt.Button btnReset;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private javax.swing.JLabel mess;
    private javax.swing.JTextField txtSTKnhan;
    private javax.swing.JTextField txtSoTienChuyen;
    // End of variables declaration//GEN-END:variables
}
