/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmtest;



import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileReader;
import java.net.InetAddress;
import java.util.Scanner;

/**
 *
 * @author Dell
 */
public class frmServer extends javax.swing.JFrame {

    /**
     * Creates new form frmServer
     */
    a gn = new a();
    public Integer tinh(Integer k,Integer n){
        if(k==0 || k==n) return 1;
        if(k==1) return n;
        return tinh(k-1,n-1)+tinh(k,n-1);
    }
    public class TuyenNhan extends Thread{
        public void run(){
            while(true){
                try {
                    String st = gn.nhan(); // 192.168.1.5:tm
                    String[] ds=st.split("[:;]");//ds[0]="192.168.1.5";ds[1]="tm"
                    String ip=ds[0];
                    String cp=ds[1];
                    String namehost = InetAddress.getLocalHost().getHostName();
                    if(cp.equals("/tm")){
                        gn.Gui(namehost, ip, 1261);
                    }
                    if(cp.equals("/ht")){
                        gn.Gui("Hoang The Huy", ip, 1261);
                    }
                    if(cp.equals("/+")){
                        //hello
                        Integer tong =0;
                        Integer max = 0;
                        Integer min = 1000000;
                        Integer dem = 0;
                        for(int i=2;i<ds.length;i++){
                            tong = tong + Integer.parseInt(ds[i]);
                            if(Integer.parseInt(ds[i])>=max) max=Integer.parseInt(ds[i]);
                            if(Integer.parseInt(ds[i])<=min) min=Integer.parseInt(ds[i]);
                            dem= dem+1;
                        }
                        gn.Gui("tong="+tong.toString(), ip, 1261);
                        gn.Gui("so lon nhat="+max.toString(), ip, 1261);
                        gn.Gui("so be nhat="+min.toString(), ip, 1261);
                        gn.Gui("so chu so client gui len="+dem.toString(), ip, 1261);
                    }
                    if(cp.equals("/note")){
                        Runtime.getRuntime().exec("notepad");
                    }
                    if(cp.equals("/excel")){
                        Runtime.getRuntime().exec("C:\\Program Files (x86)\\Microsoft Office\\Office16\\EXCEL");
                    }
                    if(cp.equals("/word")){
                        Runtime.getRuntime().exec("C:\\Program Files (x86)\\Microsoft Office\\Office16\\WINWORD");
                    }
                    if(cp.equals("/ck")){
                        //tinh to hop /ck;k;n
                       Integer tamk = Integer.parseInt(ds[2]);
                       Integer tamn = Integer.parseInt(ds[3]);
                       Integer tamkq = tinh(tamk, tamn);
                       gn.Gui("to hop"+ds[2]+"chap"+ds[3]+"kq="+tamkq.toString(), ip, 1261);
                    }
                    
                    if(cp.equals("/xoso")){
                       // Mở file data.txt trên server, gửi về nội dung của file
                        File file = new File("D:\\HK1_Năm4\\LapTrinhPhanTan\\data.txt");  
                        try (BufferedReader bufferedReader = new BufferedReader(new FileReader(file))){
                            String line = bufferedReader.readLine();
                            while (line != null) {
                              gn.Gui(line,ip,1261);  
                              line = bufferedReader.readLine();
                            }
                        } catch (Exception e) {
                        }
                    }   
                    if(cp.equals("/Quit")){
                        // tắt sever
                        // Runtime.getRuntime().exec("shutdown -s -t 30"); tắt máy sau 30giay
                       
                    }
                    list1.add(st);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }
    public frmServer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        list1 = new java.awt.List();
        txtgui = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sever");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtgui.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtguiKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtgui, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(list1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(txtgui, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            gn.MoCong(1260);
           // gn.nhan();
            TuyenNhan t1 = new TuyenNhan();
            t1.start();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtguiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtguiKeyPressed
        // TODO add your handling code here:
        try {
            if(evt.getKeyCode()==10){
            String data=InetAddress.getLocalHost().getHostAddress()+":";
            data=data+txtgui.getText();
           
            gn.Gui(data, "192.168.1.4", 1261);
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtguiKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmServer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmServer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.List list1;
    private java.awt.TextField txtgui;
    // End of variables declaration//GEN-END:variables
}
